sudo: required
services:
  - docker

before_install:
  - docker build -t urvish91/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true urvish91/react-test npm test -- --coverage

after_success:
  - docker build -t urvish91/multi-client ./client
  - docker build -t urvish91/multi-ngnix ./nginx
  - docker build -t urvish91/multi-server ./server
  - docker build -t urvish91/multi-worker ./worker
  # login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take all images and push to docker hub.
  - docker push urvish91/multi-client
  - docker push urvish91/multi-nginx
  - docker push urvish91/multi-server
  - docker push urvish91/multi-worker



